### ISSUE TITLE
Linux ubuntu 系统所遇到的问题，手动修改后已解决

### ISSUE THREAD

**Issue by Ansellyu** [MSIsunny/GenshinWishCalculator-py#1]
最初运行报错如下（文件地址错误）：
<img width="927" alt="image" src="https://user-images.githubusercontent.com/79356283/217713930-4b5452a9-2d2c-4697-9709-e17be0d1a8f9.png">
修改WishCalculatorViaPy.js第85行后如下：
<img width="383" alt="image" src="https://user-images.githubusercontent.com/79356283/217714321-1bd89655-8e54-486c-a0d8-33ae6455e676.png">
重启后解决

**Comment by MSIsunny** [comment]
感谢指出问题，\\的写法只适用windows，稍后我会修改一下
