### ISSUE TITLE
windows下启动插件出现错误

### ISSUE THREAD

**Issue by strike94** [MSIsunny/GenshinWishCalculator-py#2]
![image](https://user-images.githubusercontent.com/34638547/218679790-081a09e6-20aa-4675-8b33-c4204941247d.png)
已安装Python 3.10 ，已安装numpy，js版跟py版都会出现这个错误

**Comment by MSIsunny** [comment]
看报错是出现了语法错误，如果你是通过自己复制代码创建的.js文件，那么可以尝试clone整个项目到你的电脑，重新将两个文件放到example文件夹下。

**Comment by strike94** [comment]
直接下载zip包重新放进去正常了，但我当时是单个文件另存为下载的，奇怪了。  感谢帮助
